# Generated by Django 4.2.7 on 2026-05-01 21:54

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PosterCampaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                (
                    "destination_url",
                    models.URLField(
                        blank=True,
                        help_text="Where scanners should be redirected after the scan is recorded.",
                        null=True,
                    ),
                ),
                ("scan_count", models.PositiveIntegerField(default=0)),
                (
                    "first_scan_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "first_scan_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("first_scan_accuracy_m", models.FloatField(blank=True, null=True)),
                ("first_scan_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "poster_campaigns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PosterScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_number", models.PositiveIntegerField()),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("accuracy_m", models.FloatField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("referrer", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "poster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans",
                        to="poster_tracking.postercampaign",
                    ),
                ),
            ],
            options={
                "db_table": "poster_scans",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="postercampaign",
            index=models.Index(
                fields=["created_at"], name="poster_campaign_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="posterscan",
            index=models.Index(
                fields=["poster", "created_at"], name="poster_scan_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="posterscan",
            constraint=models.UniqueConstraint(
                fields=("poster", "scan_number"), name="unique_scan_number_per_poster"
            ),
        ),
    ]
