# Generated by Django 4.2.7 on 2025-11-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WaitlistEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="University email address", max_length=254
                    ),
                ),
                (
                    "school_slug",
                    models.CharField(
                        help_text="URL-friendly school identifier (e.g., 'university-of-waterloo')",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "waitlist_entries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["school_slug"], name="waitlist_en_school__73fb1d_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="waitlist_en_created_6e5a63_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="waitlistentry",
            constraint=models.UniqueConstraint(
                fields=("email", "school_slug"), name="unique_email_per_school"
            ),
        ),
    ]
