# Generated by Django 4.2.7 on 2025-10-12 16:01

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "club_handle",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("url", models.URLField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("location", models.CharField(max_length=255)),
                ("price", models.FloatField(blank=True, null=True)),
                ("food", models.CharField(blank=True, max_length=255, null=True)),
                ("registration", models.BooleanField(default=False)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=1536, null=True
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("club_type", models.CharField(blank=True, max_length=50, null=True)),
                ("reactions", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "events",
                "ordering": ["date", "start_time"],
            },
        ),
    ]
