# Generated by Django 4.2.7 on 2025-10-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Internal notes for this event", null=True
            ),
        ),
    ]
