# Generated by Django 4.2.7 on 2025-10-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_events_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="location",
            field=models.CharField(max_length=256),
        ),
    ]
