# Generated by Django 4.2.7 on 2025-10-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_events_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="end_time",
            field=models.TimeField(null=True),
        ),
    ]
