# Generated by Django 4.2.7 on 2025-10-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_events_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
