# Generated by Django 4.2.7 on 2025-10-18 17:31

from django.db import migrations, models
import django.utils.timezone
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_events_end_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="events",
            options={},
        ),
        migrations.RemoveField(
            model_name="events",
            name="club_handle",
        ),
        migrations.RemoveField(
            model_name="events",
            name="date",
        ),
        migrations.RemoveField(
            model_name="events",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="events",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="events",
            name="name",
        ),
        migrations.RemoveField(
            model_name="events",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="events",
            name="start_time",
        ),
        migrations.RemoveField(
            model_name="events",
            name="url",
        ),
        migrations.AddField(
            model_name="events",
            name="all_day",
            field=models.BooleanField(default=False, help_text="True"),
        ),
        migrations.AddField(
            model_name="events",
            name="categories",
            field=models.CharField(
                blank=True,
                help_text="'Career, Networking, Professional Development'",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="events",
            name="discord_handle",
            field=models.CharField(
                blank=True, help_text="'careercenter#1234'", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="events",
            name="dtend",
            field=models.DateTimeField(
                blank=True, help_text="'2024-03-20T17:00:00'", null=True
            ),
        ),
        migrations.AddField(
            model_name="events",
            name="dtend_utc",
            field=models.DateTimeField(
                blank=True, help_text="'2024-03-20T22:00:00Z'", null=True
            ),
        ),
        migrations.AddField(
            model_name="events",
            name="dtstamp",
            field=models.DateTimeField(
                default=django.utils.timezone.now, help_text="'2024-03-15T10:30:00Z'"
            ),
        ),
        migrations.AddField(
            model_name="events",
            name="dtstart",
            field=models.DateTimeField(
                default=django.utils.timezone.now, help_text="'2024-03-20T09:00:00'"
            ),
        ),
        migrations.AddField(
            model_name="events",
            name="dtstart_utc",
            field=models.DateTimeField(
                default=django.utils.timezone.now, help_text="'2024-03-20T14:00:00Z'"
            ),
        ),
        migrations.AddField(
            model_name="events",
            name="duration",
            field=models.DurationField(blank=True, help_text="'8:00:00'", null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="fb_handle",
            field=models.CharField(
                blank=True, help_text="'uwcareercenter'", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="events",
            name="ig_handle",
            field=models.CharField(
                blank=True, help_text="'uwcareercenter'", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="events",
            name="latitude",
            field=models.FloatField(blank=True, help_text="40.7128", null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="longitude",
            field=models.FloatField(blank=True, help_text="-74.0059", null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="raw_json",
            field=models.JSONField(
                default=dict,
                help_text="{'title': 'Career Fair', 'location': 'Student Center'}",
            ),
        ),
        migrations.AddField(
            model_name="events",
            name="rdate",
            field=models.JSONField(
                blank=True, help_text="['2024-03-25', '2024-04-01']", null=True
            ),
        ),
        migrations.AddField(
            model_name="events",
            name="rrule",
            field=models.TextField(
                blank=True, help_text="'FREQ=WEEKLY;BYDAY=MO'", null=True
            ),
        ),
        migrations.AddField(
            model_name="events",
            name="school",
            field=models.CharField(
                blank=True,
                help_text="'University of Waterloo'",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="events",
            name="source_image_url",
            field=models.TextField(
                blank=True,
                help_text="'https://example.com/image1.jpg,https://example.com/image2.jpg'",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="events",
            name="source_url",
            field=models.TextField(
                blank=True,
                help_text="'https://university.edu/events/career-fair'",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="events",
            name="status",
            field=models.CharField(
                blank=True,
                help_text="Event status (e.g., 'CONFIRMED', 'TENTATIVE', 'CANCELLED')",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="events",
            name="tiktok_handle",
            field=models.CharField(
                blank=True, help_text="'uwcareercenter'", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="events",
            name="title",
            field=models.TextField(
                blank=True, help_text="'Spring Career Fair 2024'", null=True
            ),
        ),
        migrations.AddField(
            model_name="events",
            name="tz",
            field=models.CharField(
                blank=True, help_text="'America/New_York'", max_length=64, null=True
            ),
        ),
        migrations.AddField(
            model_name="events",
            name="utc_end_ts",
            field=models.DateTimeField(
                blank=True, help_text="'2024-03-20T22:00:00Z'", null=True
            ),
        ),
        migrations.AddField(
            model_name="events",
            name="utc_start_ts",
            field=models.DateTimeField(
                blank=True, help_text="'2024-03-20T14:00:00Z'", null=True
            ),
        ),
        migrations.AddField(
            model_name="events",
            name="x_handle",
            field=models.CharField(
                blank=True, help_text="'UWCareerCenter'", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="events",
            name="added_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="'2024-03-15T10:30:00Z'", null=True
            ),
        ),
        migrations.AlterField(
            model_name="events",
            name="club_type",
            field=models.CharField(
                blank=True,
                help_text="WUSA, Athletics, Student Society",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="events",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="'Join us for our annual career fair featuring 50+ companies...'",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="events",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=1536,
                help_text="[0.1, -0.2, 0.3, ...]",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="events",
            name="food",
            field=models.CharField(
                blank=True,
                help_text="'Free pizza and drinks'",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="events",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="events",
            name="location",
            field=models.TextField(
                blank=True,
                help_text="'Student Center Ballroom, 123 University Ave'",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="events",
            name="price",
            field=models.FloatField(blank=True, help_text="15.99", null=True),
        ),
        migrations.AlterField(
            model_name="events",
            name="reactions",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="{'likes': 25, 'bookmarks': 12, 'shares': 8}",
            ),
        ),
        migrations.AlterField(
            model_name="events",
            name="registration",
            field=models.BooleanField(default=False, help_text="True"),
        ),
        migrations.AddIndex(
            model_name="events",
            index=models.Index(
                fields=["utc_start_ts"], name="events_utc_sta_be5330_idx"
            ),
        ),
    ]
