# Generated by Django 4.2.7 on 2025-10-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_alter_events_options_remove_events_club_handle_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="raw_json",
            field=models.JSONField(
                default=dict,
                help_text="{'title': 'Career Fair', 'location': 'Student Center'}",
            ),
        ),
        migrations.AlterField(
            model_name="events",
            name="reactions",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="{'likes': 25, 'bookmarks': 12, 'shares': 8}",
            ),
        ),
    ]
