# Generated by Django 4.2.7 on 2025-10-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0006_alter_events_raw_json_alter_events_reactions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="raw_json",
            field=models.JSONField(
                default="{}",
                help_text="{'title': 'Career Fair', 'location': 'Student Center'}",
            ),
        ),
        migrations.AlterField(
            model_name="events",
            name="reactions",
            field=models.JSONField(
                blank=True,
                default="{}",
                help_text="{'likes': 25, 'bookmarks': 12, 'shares': 8}",
            ),
        ),
    ]
