# Generated by Django 4.2.7 on 2025-10-19 03:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0008_alter_events_raw_json_alter_events_reactions"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="events",
            name="events_utc_sta_be5330_idx",
        ),
        migrations.RemoveField(
            model_name="events",
            name="utc_end_ts",
        ),
        migrations.RemoveField(
            model_name="events",
            name="utc_start_ts",
        ),
    ]
