# Generated by Django 4.2.7 on 2025-10-19 03:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0009_remove_events_events_utc_sta_be5330_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="events",
            index=models.Index(
                fields=["dtstart_utc"], name="events_dtstart_89a1ed_idx"
            ),
        ),
    ]
