# Generated by Django 4.2.7 on 2025-10-25 17:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0010_events_events_dtstart_89a1ed_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="dtstamp",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="'time created in UTC, 2024-03-15T10:30:00Z'",
            ),
        ),
    ]
