# Generated by Django 4.2.7 on 2025-10-27 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0011_alter_events_dtstamp"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventSubmission",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "screenshot_url",
                    models.URLField(help_text="S3 URL of uploaded screenshot"),
                ),
                (
                    "source_url",
                    models.URLField(help_text="URL to original event source"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "extracted_data",
                    models.JSONField(
                        blank=True,
                        help_text="Event data extracted by OpenAI",
                        null=True,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
                (
                    "created_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submission",
                        to="events.events",
                    ),
                ),
            ],
            options={
                "db_table": "event_submissions",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
