# Generated by Django 4.2.7 on 2025-10-27 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0012_eventsubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventsubmission",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who submitted this event",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
