# Generated by Django 4.2.7 on 2025-10-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0013_eventsubmission_submitted_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventsubmission",
            name="submitted_by",
            field=models.CharField(
                blank=True,
                help_text="Clerk user ID who submitted this event",
                max_length=255,
                null=True,
            ),
        ),
    ]
