# Generated by Django 4.2.7 on 2025-10-29 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0014_alter_eventsubmission_submitted_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="other_handle",
            field=models.CharField(
                blank=True,
                help_text="Other social media handle",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="eventsubmission",
            name="created_event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submission",
                to="events.events",
            ),
        ),
    ]
