# Generated by Django 4.2.7 on 2025-11-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0015_events_other_handle_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="events",
            name="events_dtstart_89a1ed_idx",
        ),
        migrations.AddIndex(
            model_name="events",
            index=models.Index(
                fields=["school", "status", "dtstart_utc", "added_at"],
                name="events_school_status_dtstart_utc_added_at_idx",
            ),
        ),
    ]
