# Generated by Django 4.2.7 on 2025-11-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0016_remove_events_events_dtstart_89a1ed_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventsubmission",
            name="submitted_by",
            field=models.CharField(
                help_text="Clerk user ID who submitted this event", max_length=255
            ),
        ),
    ]
