# Generated by Django 4.2.7 on 2025-11-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0017_alter_eventsubmission_submitted_by"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="events",
            name="events_school_status_dtstart_utc_added_at_idx",
        ),
        migrations.AddIndex(
            model_name="events",
            index=models.Index(
                fields=["school", "status", "dtstart_utc", "dtend_utc", "added_at"],
                name="events_school_status_dtstart_utc_dtend_utc_added_at_idx",
            ),
        ),
    ]
