# Generated by Django 4.2.7 on 2025-11-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "events",
            "0018_remove_events_events_school_status_dtstart_utc_added_at_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="events",
            name="events_school_status_dtstart_utc_dtend_utc_added_at_idx",
        ),
        migrations.AddIndex(
            model_name="events",
            index=models.Index(
                fields=["school", "status", "dtend_utc"],
                name="events_school_status_dtend_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="events",
            index=models.Index(
                condition=models.Q(("dtend_utc__isnull", True)),
                fields=["school", "status", "dtstart_utc"],
                name="events_school_status_dtstart_nullend_idx",
            ),
        ),
    ]
