# Generated by Django 4.2.7 on 2025-11-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_remove_events_events_school_status_dtstart_utc_dtend_utc_added_at_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='categories',
            field=models.JSONField(blank=True, default=list, help_text="List of event categories (e.g. ['Academic', 'Cultural'])"),
        ),
    ]
