# Generated by Django 4.2.7 on 2025-11-04 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0020_alter_events_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="events",
            name="embedding",
        ),
        migrations.CreateModel(
            name="EventDates",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "dtstart",
                    models.DateTimeField(
                        help_text="Local start time for this occurrence"
                    ),
                ),
                (
                    "dtend",
                    models.DateTimeField(
                        blank=True,
                        help_text="Local end time for this occurrence",
                        null=True,
                    ),
                ),
                (
                    "dtstart_utc",
                    models.DateTimeField(
                        db_index=True, help_text="UTC start time for this occurrence"
                    ),
                ),
                (
                    "dtend_utc",
                    models.DateTimeField(
                        blank=True,
                        help_text="UTC end time for this occurrence",
                        null=True,
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        blank=True, help_text="Duration of this occurrence", null=True
                    ),
                ),
                (
                    "tz",
                    models.CharField(
                        blank=True,
                        help_text="'America/New_York'",
                        max_length=64,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        help_text="Reference to the parent event",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_dates",
                        to="events.events",
                    ),
                ),
            ],
            options={
                "db_table": "event_dates",
                "ordering": ["dtstart_utc"],
                "indexes": [
                    models.Index(
                        fields=["dtstart_utc"], name="eventdates_dtstart_utc_idx"
                    ),
                    models.Index(fields=["dtend_utc"], name="eventdates_dtend_utc_idx"),
                    models.Index(
                        fields=["event", "dtstart_utc"],
                        name="eventdates_event_dtstart_idx",
                    ),
                ],
            },
        ),
    ]
