# Generated by Django 4.2.7 on 2025-11-05 00:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0021_remove_events_embedding_eventdates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventsubmission",
            name="source_url",
            field=models.URLField(
                blank=True, help_text="URL to original event source", null=True
            ),
        ),
    ]
