# Generated by Django 4.2.7 on 2025-11-05 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0022_alter_eventsubmission_source_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventsubmission",
            name="source_url",
            field=models.URLField(help_text="URL to original event source"),
        ),
    ]
