# Generated by Django 4.2.7 on 2025-11-05 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0023_alter_eventsubmission_source_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventInterest",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "user_id",
                    models.CharField(
                        db_index=True,
                        help_text="Clerk user ID of the interested user",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        help_text="Reference to the event",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interests",
                        to="events.events",
                    ),
                ),
            ],
            options={
                "db_table": "event_interests",
                "ordering": ["-created_at"],
                "unique_together": {("event", "user_id")},
            },
        ),
    ]
