# Generated by Django 4.2.7 on 2025-11-06 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0025_add_events_query_optimization_index"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="events",
            name="events_query_opt_idx",
        ),
        migrations.AddIndex(
            model_name="events",
            index=models.Index(
                fields=["school", "status", "dtend_utc", "dtstart_utc"],
                name="events_school_status_dtend_utc_dtstart_utc_idx",
            ),
        ),
    ]
