# Generated by Django 4.2.7 on 2025-11-07 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0027_ignoredpost"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="events",
            name="events_school_status_dtend_idx",
        ),
        migrations.RemoveIndex(
            model_name="events",
            name="events_school_status_dtstart_nullend_idx",
        ),
        migrations.RemoveIndex(
            model_name="events",
            name="events_school_status_dtend_utc_dtstart_utc_idx",
        ),
        migrations.RemoveField(
            model_name="eventdates",
            name="dtend",
        ),
        migrations.RemoveField(
            model_name="eventdates",
            name="dtstart",
        ),
        migrations.RemoveField(
            model_name="events",
            name="all_day",
        ),
        migrations.RemoveField(
            model_name="events",
            name="dtend",
        ),
        migrations.RemoveField(
            model_name="events",
            name="dtend_utc",
        ),
        migrations.RemoveField(
            model_name="events",
            name="dtstamp",
        ),
        migrations.RemoveField(
            model_name="events",
            name="dtstart",
        ),
        migrations.RemoveField(
            model_name="events",
            name="dtstart_utc",
        ),
        migrations.RemoveField(
            model_name="events",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="events",
            name="rdate",
        ),
        migrations.RemoveField(
            model_name="events",
            name="rrule",
        ),
        migrations.RemoveField(
            model_name="events",
            name="tz",
        ),
        migrations.RemoveField(
            model_name="eventsubmission",
            name="extracted_data",
        ),
        migrations.RemoveField(
            model_name="eventsubmission",
            name="screenshot_url",
        ),
        migrations.RemoveField(
            model_name="eventsubmission",
            name="source_url",
        ),
        migrations.RemoveField(
            model_name="eventsubmission",
            name="status",
        ),
    ]
