# Generated by Django 4.2.7 on 2025-11-07 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0028_remove_events_events_school_status_dtend_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="events",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="events",
            name="longitude",
        ),
    ]
