# Generated by Django 4.2.7 on 2025-01-XX XX:XX

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0029_remove_events_latitude_remove_events_longitude"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventsubmission",
            name="admin_notes",
        ),
    ]
