# Generated by Django 4.2.7 on 2025-11-08 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_remove_eventsubmission_admin_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='raw_json',
        ),
    ]
