# Generated by Django 4.2.7 on 2025-11-30 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0032_alter_eventdates_id_alter_eventinterest_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="comments_count",
            field=models.IntegerField(
                default=0, help_text="Number of comments on the original post"
            ),
        ),
        migrations.AddField(
            model_name="events",
            name="likes_count",
            field=models.IntegerField(
                default=0, help_text="Number of likes on the original post"
            ),
        ),
        migrations.AddField(
            model_name="events",
            name="posted_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="When the event was originally posted (e.g., on Instagram)",
                null=True,
            ),
        ),
    ]
