# Generated by Django 4.2.7 on 2025-11-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0032_alter_eventdates_id_alter_eventinterest_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="posted_at",
            field=models.DateTimeField(
                blank=True, help_text="Posted at UTC", null=True
            ),
        ),
    ]
