# Generated by Django 4.2.7 on 2025-12-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_events_comments_count_events_likes_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='posted_at',
            field=models.DateTimeField(blank=True, help_text='When the event was originally posted (e.g., on Instagram)', null=True),
        ),
    ]
