# Generated by Django 4.2.7 on 2025-12-04 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_events_comments_count_events_likes_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='source_url',
            field=models.TextField(blank=True, help_text="'https://university.edu/events/career-fair'", null=True, unique=True),
        ),
    ]
