# Generated by Django 4.2.7 on 2025-12-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0034_alter_events_source_url"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="events",
            index=models.Index(
                fields=["status", "school"], name="events_status_school_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="events",
            index=models.Index(fields=["status"], name="events_status_idx"),
        ),
        migrations.AddIndex(
            model_name="events",
            index=models.Index(fields=["added_at"], name="events_added_at_idx"),
        ),
        migrations.AddIndex(
            model_name="events",
            index=models.Index(fields=["price"], name="events_price_idx"),
        ),
    ]
