# Generated by Django 4.2.7 on 2025-12-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0035_add_events_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventsubmission",
            name="submitted_by_email",
            field=models.EmailField(
                blank=True,
                help_text="Email of the user at time of submission",
                max_length=255,
                null=True,
            ),
        ),
    ]
