# Generated by Django 4.2.7 on 2026-01-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0036_add_submitted_by_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='source_url',
            field=models.TextField(blank=True, help_text="'https://university.edu/events/career-fair'", null=True),
        ),
    ]
