# Generated by Django 4.2.7 on 2026-01-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0037_alter_events_source_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='posted_at',
            field=models.DateTimeField(blank=True, help_text='When the event was originally posted (e.g., on Instagram)', null=True),
        ),
    ]
