# Generated by Django 4.2.7 on 2025-10-12 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventPromotion",
            fields=[
                (
                    "event",
                    models.OneToOneField(
                        help_text="Event being promoted",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="promotion",
                        serialize=False,
                        to="events.events",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this promotion is currently active",
                    ),
                ),
                (
                    "promoted_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this event was promoted",
                    ),
                ),
                (
                    "promoted_by",
                    models.CharField(
                        help_text="Who promoted this event (username or email)",
                        max_length=100,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When this promotion expires (null = no expiration)",
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        db_index=True,
                        default=10,
                        help_text="Priority level (1-10, higher = more prominent)",
                    ),
                ),
                (
                    "promotion_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("featured", "Featured"),
                            ("urgent", "Urgent"),
                            ("sponsored", "Sponsored"),
                        ],
                        default="standard",
                        help_text="Type of promotion",
                        max_length=50,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes about this promotion"
                    ),
                ),
            ],
            options={
                "db_table": "event_promotions",
                "ordering": ["-priority", "-promoted_at"],
            },
        ),
    ]
