# Generated by Django 4.2.7 on 2025-10-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clubs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("club_name", models.CharField(max_length=100, unique=True)),
                ("categories", models.CharField(max_length=255)),
                ("club_page", models.URLField(blank=True, null=True)),
                ("ig", models.URLField(blank=True, null=True)),
                ("discord", models.URLField(blank=True, null=True)),
                (
                    "club_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("WUSA", "WUSA"),
                            ("Athletics", "Athletics"),
                            ("Student Society", "Student Society"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "clubs",
            },
        ),
    ]
