# Generated by Django 4.2.7 on 2025-10-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubs",
            name="categories",
            field=models.CharField(max_length=512),
        ),
    ]
