# Generated by Django 4.2.7 on 2025-10-16 04:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0002_alter_clubs_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubs",
            name="categories",
            field=models.JSONField(default=list),
        ),
    ]
