# Generated by Django 4.2.7 on 2025-10-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0003_alter_clubs_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubs",
            name="categories",
            field=models.JSONField(default="[]"),
        ),
    ]
