# Generated by Django 4.2.7 on 2025-11-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0005_alter_clubs_categories"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="clubs",
            index=models.Index(fields=["club_name"], name="clubs_club_name_idx"),
        ),
    ]
