# Generated by Django 4.2.7 on 2025-08-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clubs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("club_name", models.CharField(max_length=100, unique=True)),
                ("categories", models.CharField(max_length=255)),
                ("club_page", models.URLField(blank=True, null=True)),
                ("ig", models.URLField(blank=True, null=True)),
                ("discord", models.URLField(blank=True, null=True)),
            ],
            options={
                "db_table": "clubs",
            },
        ),
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "club_handle",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("url", models.URLField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("location", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "events",
            },
        ),
    ]
