# Generated by Django 4.2.7 on 2025-09-21 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("example", "0007_merge_20250914_1558"),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE events ADD COLUMN embedding vector(1536);",
            reverse_sql="ALTER TABLE events DROP COLUMN embedding;",
        ),
    ]
