# Generated by Django 4.2.7 on 2025-09-24 00:00

from django.db import migrations
from example.embedding_utils import generate_event_embedding


def repopulate_embeddings(apps, schema_editor):
    """
    Repopulate all events with embeddings, including those that already have them.
    This ensures consistency with the current embedding generation logic.
    """
    with schema_editor.connection.cursor() as cursor:
        # Get all events
        cursor.execute("""
            SELECT id, name, location, food, club_handle, price, registration 
            FROM events 
        """)
        events = cursor.fetchall()
        
        total_events = len(events)
        print(f"Regenerating embeddings for {total_events} events...")
        
        for i, (event_id, name, location, food, club_handle, price, registration) in enumerate(events, 1):
            try:
                # Generate embedding for the event using the same format as scraper
                event_data = {
                    'name': name or '',
                    'location': location or '',
                    'food': food or '',
                    'club_handle': club_handle or '',
                    'price': price,
                    'registration': registration or False,
                }
                
                embedding = generate_event_embedding(event_data)
                
                # Update the event with the embedding
                cursor.execute(
                    "UPDATE events SET embedding = %s::vector WHERE id = %s",
                    [embedding, event_id]
                )
                
                if i % 10 == 0:  # Progress indicator
                    print(f"Processed {i}/{total_events} events...")
                
            except Exception as e:
                print(f"Error generating embedding for event {event_id} ({name}): {e}")
                continue
        
        print(f"Completed regenerating embeddings for {total_events} events.")


def reverse_repopulate_embeddings(apps, schema_editor):
    """
    Remove embeddings from events.
    """
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("UPDATE events SET embedding = NULL")
        print("Removed all embeddings from events.")


class Migration(migrations.Migration):

    dependencies = [
        ("example", "0009_populate_embeddings"),
    ]

    operations = [
        migrations.RunPython(
            repopulate_embeddings,
            reverse_repopulate_embeddings,
        ),
    ]
