# Generated by Django 4.2.7 on 2025-09-24 20:33

from django.db import migrations, models
import pgvector.django.vector


class Migration(migrations.Migration):
    dependencies = [
        ("example", "0011_regenerate_embeddings_simple"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="added_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=1536, null=True
            ),
        ),
    ]
