# Generated by Django 4.2.7 on 2025-09-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("example", "0012_events_added_at_events_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="club_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
