# Generated by Django 4.2.7 on 2025-10-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("example", "0014_update_null_embeddings"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="reactions",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
