# Generated by Django 4.2.7 on 2025-10-04 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("example", "0015_add_description_field"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="events",
            options={"ordering": ["date", "start_time"]},
        ),
    ]
