# Generated by Django 4.2.7 on 2025-10-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("example", "0019_add_unsubscribe_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="newslettersubscriber",
            name="unsubscribe_reason",
            field=models.CharField(
                blank=True,
                help_text="Reason provided when user unsubscribed",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="unsubscribed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
