# Generated by Django 4.2.7 on 2026-04-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ig_user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ig_username', models.CharField(blank=True, max_length=100, null=True)),
                ('username_resolved', models.BooleanField(default=False)),
                ('dispatch_sent', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'automate_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ig_username', models.CharField(db_index=True, max_length=100)),
                ('github_run_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('error', 'Error'), ('no_posts', 'No Posts')], default='running', max_length=20)),
                ('posts_fetched', models.IntegerField(default=0)),
                ('posts_new', models.IntegerField(default=0)),
                ('events_extracted', models.IntegerField(default=0)),
                ('events_saved', models.IntegerField(default=0)),
                ('pinned_post_warning', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scrape_runs',
                'ordering': ['-started_at'],
            },
        ),
    ]
