# Generated by Django 4.2.7 on 2025-10-12 16:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "unsubscribe_token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "unsubscribe_reason",
                    models.CharField(
                        blank=True,
                        help_text="Reason provided when user unsubscribed",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("unsubscribed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "newsletter_subscribers",
                "ordering": ["-subscribed_at"],
            },
        ),
    ]
