# Generated by Django 4.2.7 on 2025-10-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0003_add_encrypted_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newslettersubscriber",
            name="email_hash",
            field=models.CharField(
                help_text="SHA-256 hash of the email for uniqueness checks",
                max_length=128,
                unique=True,
            ),
        ),
    ]
